name: Build, Publish, and Deploy Docker Images

on:
  push:
    branches:
      - develop
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and Publish ${{ matrix.image.name }}
    strategy:
      fail-fast: false
      matrix: 
          image:
            - name: realm
              build_realm: "TRUE"
              build_world: "FALSE"
            - name: world
              build_realm: "FALSE"
              build_world: "TRUE"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Docker tag
        run: |
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=test" >> $GITHUB_ENV
          fi

      - name: Extract REPO_NAME
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ matrix.image.name }}:${{ env.TAG }} \
            --target ${{ matrix.image.name }} \
            --build-arg BUILD_WORLD=${{ matrix.image.build_world }} \
            --build-arg BUILD_REALM=${{ matrix.image.build_realm }} \
            .

      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/${{ matrix.image.name }}:${{ env.TAG }}

  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    name: Deploy ${{ matrix.image.name }}
    strategy:
      fail-fast: false
      matrix: 
          image:
            - name: realm
            - name: world
    steps:
      - name: Extract REPO_NAME
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
      - name: Deploy to Dokku
        run: |
            if [[ "${{ github.ref_name }}" == "master" ]]; then
              SERVER_IP=${{ vars.ORG_SERVER_IP }}
              TAG=latest
            else
              SERVER_IP=${{ vars.ORG_TEST_SERVER_IP }}
              TAG=test
            fi
            ssh dokku@${SERVER_IP} tags:set ${{ matrix.image.name }} $TAG
            ssh dokku@${SERVER_IP} docker-options:add ${{ matrix.image.name }} deploy "--restart always"
            ssh dokku@${SERVER_IP} git:from-image --force-rebuild ${{ matrix.image.name }} ghcr.io/${{ env.REPO_NAME }}/${{ matrix.image.name }}:$TAG
            ssh dokku@${SERVER_IP} ps:restart ${{ matrix.image.name }}

